# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: docker.io/postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    #   - ./db:/var/lib/postgresql/data
    #   - ./dump-ebdb-202409241743:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      
    ports:
      - 5432:5432